name: Sync Data With Upstream Repo

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: csianglim/github-sync@master
      with:
        source_repo: "ishaberry/Covid19Canada"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
