name: Sync Data With Upstream Repo

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: csianglim/github-sync@master
      with:
        source_repo: "ishaberry/Covid19Canada"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
